const { SlashCommandBuilder } = require('discord.js');
const { GoogleSpreadsheet } =  require('google-spreadsheet');
const {JWT} = require('google-auth-library');
const fs = require('fs');

var serviceAccountAuth;
var doc;

module.exports = {
    data: new SlashCommandBuilder().setName('export_sheet').setDescription('Get a download for the sheet'),
    run: async({ interaction }) => {
        await interaction.deferReply();

        await initSheet();
        const CSVBuffer = await doc.sheetsByIndex[4].downloadAsCSV(true);

  


        await interaction.editReply({
            files: [{
                attachment: CSVBuffer,
                name: 'export.csv'
            }]
        });
    },
}

async function initSheet(){
    serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
        keyFile: process.env.GOOGLE_PRIVATE_KEY,
        scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
    doc = new GoogleSpreadsheet(process.env.SPREADSHEET_ID, serviceAccountAuth);
    await doc.loadInfo(); // loads document properties and worksheets
  
}