const { SlashCommandBuilder } = require('discord.js');
const warSchema = require('./../models/wars');
const MemberSchema = require('./../models/war_data');
const { GoogleSpreadsheet } =  require('google-spreadsheet');
const {JWT} = require('google-auth-library');
const { parse } = require('dotenv');

var serviceAccountAuth;
var doc;
var sheetIndex = 1;
const reg = /Aug (1[0-9]|2[0-9]|3[01])/;


module.exports = {
    data: new SlashCommandBuilder().setName('idkname').setDescription('Gets your clan score!'), 
    run: async({ interaction }) => {
        await interaction.deferReply();
        await initSheet();
        const sheet = doc.sheetsByIndex[sheetIndex];
        const rows = await sheet.getRows(); // can pass in { limit, offset }

        let scores = [];
        let names = [];
        const nameWidth = 16; // adjust as needed
        const warScoreWidth = 6; // adjust as needed
        const donosScoreWidth = 7; // adjust as needed
        const totalScoreWidth = 8; // adjust as needed
        const Avg_TarWidth = 9;
        for (const row of rows) {
            let name = row.get('Name').padEnd(nameWidth, ' ');
            let warScore = row.get('Total war score').toString().padEnd(warScoreWidth, ' ');
            let donosScore = row.get('Donos score').toString().padEnd(donosScoreWidth, ' ');
            let totalScore = row.get('Total score');
            //console.log(totalScore);
            if(!isNaN(parseInt(totalScore))){
                let nameTag = row.get('Player tag');
                const query = { tag: nameTag, timestamp: { $regex: reg } };
                let member = await MemberSchema.find(query);
                //find all members after August 10th 
                
                let attack = 0;
                let counter = 0;
                for(const mem of member){
                    for(const atk of mem.attacks){
                        attack += atk.opponentMapPosition;
                        counter++;
                    }
                }
                let avgTar = attack/counter;
                avgTar = (avgTar).toFixed(2).toString().padEnd(Avg_TarWidth, ' ');
                names.push(`${name}${warScore}${donosScore}${avgTar}`);
                //console.log(parseInt(totalScore));
                scores.push(parseInt(totalScore));
            }
        }
        const { sortedScores, sortedNames } = sortScoresAndNames(scores, names);
  
        //loop through rows
        let arr = [];
        let startStr = "No. Name            War   Dono   Avg_Tar  Total\n";
        let message = "```"+startStr;
        let counter = 0;
        for (const row of sortedNames) {
            let formattedScore = sortedScores[counter].toString().padEnd(totalScoreWidth, ' ');
            let rank = (counter + 1).toString().padEnd(4, ' ');
            //console.log(sortedScores[counter]);
            message += rank + row + formattedScore + "\n";
            if(message.length > 1800){
                message += "```";
                arr.push(message);
                message = "```";
            }
            counter++;
        }
        if(message.length > 3){
            message += "```";
            arr.push(message);
        }
        await interaction.editReply("Here is the clan score: ");
        for(const msg of arr){
            await interaction.channel.send(msg);
        }
        

    },
    Globalcooldown_5s: true,
}




function sortScoresAndNames(scores, names) {
    // Create an array of pairs (score, name)
    let pairedArray = scores.map((score, index) => [score, names[index]]);

    // Sort the paired array based on the score in descending order
    pairedArray.sort((a, b) => b[0] - a[0]);

    // Separate the paired array back into scores and names arrays
    let sortedScores = pairedArray.map(pair => pair[0]);
    let sortedNames = pairedArray.map(pair => pair[1]);

    return { sortedScores, sortedNames };
}

async function initSheet(){
    serviceAccountAuth = new JWT({
        // env var values here are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
        keyFile: process.env.GOOGLE_PRIVATE_KEY,
        scopes: ['https://www.googleapis.com/auth/spreadsheets'],
    });
    doc = new GoogleSpreadsheet(process.env.SPREADSHEET_ID, serviceAccountAuth);
    await doc.loadInfo(); // loads document properties and worksheets
  
}